repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0  # Or a newer stable version
    hooks:
    -   id: black
        args: [--line-length=88]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0   # Or a newer stable version
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]
